description: "A simple console application."
name: "sense_model"
version: "0.0.3"
dependencies: 
  build: "^0.3.0"
  yaml: "2.1.10"
  json_schema: 
    git: "git://github.com/vadimtsushko/json_schema.git"
dev_dependencies: 
  dogma_json_schema: "any"
