name: sense_model
version: 0.0.1
description: A simple console application.
dependencies:
  yaml: 2.1.10
  json_schema:
    git:
      'git://github.com/vadimtsushko/json_schema.git'
  build: ^0.3.0
dev_dependencies:
  dogma_json_schema: any

