// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.app_config;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class AppConfig {
  /// Qlik Sense host
  @Serialize.field('host')
  String host;

  /// Qlik Sense application ID
  @Serialize.field('id')
  String id;

  /// App name
  @Serialize.field('name')
  String name;
  @Serialize.field('lang', optional: true)
  String lang;

  /// Фильтр по умолчанию на основе системной даты
  @Serialize.field('useCurrentDate', optional: true)
  bool useCurrentDate;

  /// Год для фильтра по умолчанию
  @Serialize.field('currentYear', optional: true)
  int currentYear;

  /// Месяц для фильтра по умолчанию
  @Serialize.field('currentMonth', optional: true)
  int currentMonth;
}
