// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.chart_definition;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'iv_dimension.dart';
import 'iv_measure.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class ChartDefinition {
  /// Тип визуализации
  String chartType;

  /// Код элемента визуализации
  String chartId;

  /// Список измерений
  List<IvDimension> dimensions;

  /// Список мер
  List<IvMeasure> measures;
}
