// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.chart_definition;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';
import 'iv_dimension.dart';
import 'iv_measure.dart';
import 'nx_bar_grouping.dart';
import 'nx_data_point.dart';
import 'nx_dimension_axis.dart';
import 'nx_donut.dart';
import 'nx_legend.dart';
import 'nx_measure_axis.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class ChartDefinition {
  /// Тип визуализации
  @Serialize.field('chartType')
  String chartType;

  /// Код элемента визуализации
  @Serialize.field('chartId')
  String chartId;

  /// Список измерений
  @Serialize.field('dimensions', optional: true)
  List<IvDimension> dimensions;

  /// Код таблицы селектора для множественного выбора мер (используется вместо
  /// списка мер в генераторе отчетов)
  @Serialize.field('measuresSelector', optional: true)
  String measuresSelector;
  @Serialize.field('hierarchySelectors', optional: true)
  List<String> hierarchySelectors;

  /// Список мер
  @Serialize.field('measures', optional: true)
  List<IvMeasure> measures;
  @Serialize.field('title', optional: true)
  String title;
  @Serialize.field('showTitles', optional: true)
  bool showTitles;
  @Serialize.field('subtitle', optional: true)
  String subtitle;
  @Serialize.field('footnote', optional: true)
  String footnote;

  /// Bar grouping settings
  @Serialize.field('barGrouping', optional: true)
  NxBarGrouping barGrouping;

  /// Piechart donut properties
  @Serialize.field('donut', optional: true)
  NxDonut donut;

  /// Data point settings
  @Serialize.field('dataPoint', optional: true)
  NxDataPoint dataPoint;

  /// Legend settings
  @Serialize.field('legend', optional: true)
  NxLegend legend;

  /// Legend settings
  @Serialize.field('dimensionAxis', optional: true)
  NxDimensionAxis dimensionAxis;

  /// Legend settings
  @Serialize.field('measureAxis', optional: true)
  NxMeasureAxis measureAxis;

  /// Sets the null value presentation
  @Serialize.field('nullMode', optional: true)
  Map nullMode;

  /// Removes zero values.Default is false.
  @Serialize.field('suppressZero', optional: true)
  bool suppressZero;

  /// Removes missing values.Default is false.
  @Serialize.field('suppressMissing', optional: true)
  bool suppressMissing;

  /// To enable the sorting by ascending or descending order in the values of a
  /// measure.This property applies to pivot tables and stacked pivot tables.
  @Serialize.field('sortbyYValue', optional: true)
  int sortbyYValue;

  /// Order the columns of the hypercube should be sorted. The index of the
  /// pseudo-dimension (if any) is -1.
  @Serialize.field('interColumnSortOrder', optional: true)
  List<int> interColumnSortOrder;

  /// Orientation settings. If vertical, the dimension axis can only be docked on
  /// bottom or top and measure axis on left or right
  @Serialize.field('orientation', optional: true)
  String orientation;
}
