// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-08-18 16:04:21.241340

library sense_model.src.models.iv_attr_expression;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvAttrExpression {
  /// Код
  @Serialize.field('expression')
  String expression;

  /// Список параметров для выражения - шаблона
  @Serialize.field('params', optional: true)
  List<String> params;

  /// Статическая ли это выражение
  @Serialize.field('inPlace', optional: true)
  bool inPlace;

  /// Статическая ли это выражение
  @Serialize.field('isStatic', optional: true)
  bool isStatic;
}
