// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.iv_attr_expression;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvAttrExpression {
  /// Код
  @Serialize.field('expression')
  String expression;

  /// Статическая ли это выражение
  @Serialize.field('inPlace', optional: true)
  bool inPlace;

  /// Статическая ли это выражение
  @Serialize.field('isStatic', optional: true)
  bool isStatic;
}
