// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.iv_dimension;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';
import 'iv_measure.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvDimension {
  /// Статическое ли это измерение
  @Serialize.field('isStatic')
  bool isStatic;

  /// Динамически создаваемая иерархия
  @Serialize.field('dynamicHyerarchy', optional: true)
  bool dynamicHyerarchy;

  /// Необходимо проверить условие отображения колонки
  @Serialize.field('contitional', optional: true)
  String contitional;

  /// Выражение сортировки (по убыванию)
  @Serialize.field('sortByExpression', optional: true)
  IvMeasure sortByExpression;

  /// Показывать колонку (рантайм параметр)
  @Serialize.field('visible', optional: true)
  bool visible;

  /// Код поля (если измерение статическое), либо название динамической таблицы,
  /// откуда будет получен текущий код поля
  @Serialize.field('key')
  String key;
}
