// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.iv_dimension;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';
import 'iv_attr_expression.dart';
import 'iv_measure.dart';
import 'nx_other_total_spec_prop.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvDimension {
  /// Статическое ли это измерение
  @Serialize.field('isStatic', optional: true)
  bool isStatic;

  /// Динамически создаваемая иерархия
  @Serialize.field('dynamicHyerarchy', optional: true)
  bool dynamicHyerarchy;

  /// Необходимо проверить условие отображения колонки
  @Serialize.field('contitional', optional: true)
  String contitional;

  /// Ширина колонки
  @Serialize.field('width', optional: true)
  int width;

  /// Выражение сортировки (по убыванию)
  @Serialize.field('sortByExpression', optional: true)
  IvMeasure sortByExpression;

  /// Показывать колонку (рантайм параметр)
  @Serialize.field('visible', optional: true)
  bool visible;

  /// Sets the dimension limits. Each dimension of a hypercube is configured
  /// separately. Just stub for now. Should add type in future
  @Serialize.field('qOtherTotalSpec', optional: true)
  NxOtherTotalSpecProp qOtherTotalSpec;
  @Serialize.field('backgroundColor', optional: true)
  IvAttrExpression backgroundColor;
  @Serialize.field('fontColor', optional: true)
  IvAttrExpression fontColor;

  /// Код поля (если измерение статическое), либо название динамической таблицы,
  /// откуда будет получен текущий код поля
  @Serialize.field('key')
  String key;
}
