// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-12-06 11:14:57.399257

library sense_model.src.models.iv_expression_param;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvExpressionParam {
  /// Значение параметра
  @Serialize.field('value')
  String value;

  /// Тип параметра
  @Serialize.field('valueType', optional: true)
  String valueType;

  /// Тип обработки значения
  @Serialize.field('contentType', optional: true)
  String contentType;
}
