// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-11-15 11:30:01.492953

library sense_model.src.models.iv_expression_param;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvExpressionParam {
  /// Значение параметра
  @Serialize.field('value')
  String value;

  /// Тип параметра
  @Serialize.field('valueType', optional: true)
  String valueType;

  /// Тип обработки значения
  @Serialize.field('contentType', optional: true)
  String contentType;
}
