// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.iv_filter_param;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvFilterParam {
  /// Поле для фильтра
  String fieldName;

  /// Значение фильтра
  String fieldValue;
}
