// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-04 19:55:17.892601

library sense_model.src.models.iv_filter_param;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvFilterParam {
  /// Поле для фильтра
  String fieldName;

  /// Значение фильтра
  String fieldValue;
}
