// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-12-06 11:14:57.399257

library sense_model.src.models.iv_filter_param;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvFilterParam {
  /// Поле для фильтра
  String fieldName;

  /// Значение фильтра
  String fieldValue;
}
