// Generated by Dogma Dart. DO NOT MODIFY!
// 2017-01-24 14:53:01.774400

library sense_model.src.models.iv_key_value_pair;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvKeyValuePair {
  /// Код
  String key;

  /// Значение
  String value;
}
