// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-08-19 12:36:50.431303

library sense_model.src.models.iv_key_value_pair;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvKeyValuePair {
  /// Код
  String key;

  /// Значение
  String value;
}
