// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-07 13:16:59.317938

library sense_model.src.models.iv_key_value_pair;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvKeyValuePair {
  /// Код
  String key;

  /// Значение
  String value;
}
