// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-04 19:55:17.892601

library sense_model.src.models.iv_list_item;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvListItem {
  /// Код значения
  String id;

  /// Отображаемое значение
  String title;
}
