// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-11-15 11:30:01.492953

library sense_model.src.models.iv_measure_type;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';
import 'locale_display_name.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvMeasureType {
  /// Код семейства
  @Serialize.field('key')
  String key;

  /// Значение отображаемое в списках выбора
  @Serialize.field('displayName')
  String displayName;
  @Serialize.field('localeDisplayName', optional: true)
  LocaleDisplayName localeDisplayName;

  /// Формат выражения
  @Serialize.field('format', optional: true)
  String format;

  /// Выражения этого типа относятся к плановым показателям
  @Serialize.field('isPlan', optional: true)
  bool isPlan;
}
