// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-07 13:16:59.317938

library sense_model.src.models.iv_measure_type;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class IvMeasureType {
  /// Код семейства
  @Serialize.field('key')
  String key;

  /// Значение отображаемое в списках выбора
  @Serialize.field('displayName')
  String displayName;

  /// Выражения этого типа относятся к плановым показателям
  @Serialize.field('isPlan', optional: true)
  bool isPlan;
}
