// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-11-15 11:30:01.492953

library sense_model.src.models.locale_display_name;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class LocaleDisplayName {
  /// English
  @Serialize.field('en')
  String en;

  /// French
  @Serialize.field('fr', optional: true)
  String fr;

  /// Deutch
  @Serialize.field('de', optional: true)
  String de;
}
