// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-08-18 16:04:21.241340

library sense_model.src.models.nx_attr_expr_def;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxAttrExprDef {
  /// Definition of the attribute expression. Example: Max(OrderID)
  String qExpression;

  /// Type of attribute expression
  String id;
}
