// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-12-06 11:14:57.399257

library sense_model.src.models.nx_attr_expr_def;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxAttrExprDef {
  /// Definition of the attribute expression. Example: Max(OrderID)
  String qExpression;

  /// Type of attribute expression
  String id;
}
