// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-02 10:38:39.164902

library sense_model.src.models.nx_attr_expr_def;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxAttrExprDef {
  /// Definition of the attribute expression. Example: Max(OrderID)
  String qExpression;

  /// Type of attribute expression
  String id;
}
