// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-07 13:16:59.317938

library sense_model.src.models.nx_bar_grouping;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxBarGrouping {
  /// Bar grouping settings
  String grouping;
}
