// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-04 19:55:17.892601

library sense_model.src.models.nx_bar_grouping;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxBarGrouping {
  /// Bar grouping settings
  String grouping;
}
