// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-08-19 12:36:50.431303

library sense_model.src.models.nx_bar_grouping;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxBarGrouping {
  /// Bar grouping settings
  String grouping;
}
