// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.nx_custom_error_message;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxCustomErrorMessage {
  /// Set to customize the calculation condition unfilled message
  String calcCond;
}
