// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-11-11 17:56:46.338198

library sense_model.src.models.nx_custom_error_message;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxCustomErrorMessage {
  /// Set to customize the calculation condition unfilled message
  String calcCond;
}
