// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.nx_container_entry;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';
import 'nx_info.dart';
import 'nx_meta.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxContainerEntry {
  /// Information about the object
  @Serialize.field('qInfo')
  NxInfo qInfo;

  /// Information about the object
  @Serialize.field('qMeta', optional: true)
  NxMeta qMeta;
}
