// Generated by Dogma Dart. DO NOT MODIFY!
// 2017-01-17 11:59:03.825591

library sense_model.src.models.nx_custom_error_message;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxCustomErrorMessage {
  /// Set to customize the calculation condition unfilled message
  String calcCond;
}
