// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.nx_data_point;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxDataPoint {
  /// Set to display data points on line series. Only used if there is at least
  /// one measure with type set to line.
  bool show;
}
