// Generated by Dogma Dart. DO NOT MODIFY!
// 2017-01-24 14:53:01.774400

library sense_model.src.models.nx_donut;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxDonut {
  /// Set to present the pie chart as a donut.
  bool showAsDonut;
}
