// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-08-18 16:04:21.241340

library sense_model.src.models.nx_donut;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxDonut {
  /// Set to present the pie chart as a donut.
  bool showAsDonut;
}
