// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.nx_dimension;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'nx_inline_dimension_def.dart';
import 'nx_value_expr.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxDimension {
  /// Should be set to `dimension` simetimes
  String type;

  /// Refers to a dimension stored in the library.
  String qLibraryId;

  /// Refers to a dimension stored in the hypercube.
  NxInlineDimensionDef qDef;

  /// If set to true, no null values are returned.
  bool qNullSuppression;

  /// If set to true, all dimension values are shown.
  bool qShowAll;

  /// This property is used when some dimension limits are set.
  String qOtherLabel;

  /// If this property is set, the total of the calculated values is returned.
  String qTotalLabel;

  /// Sets the dimension limits. Each dimension of a hypercube is configured
  /// separately. Just stub for now. Should add type in future
  String qOtherTotalSpec;

  /// Specifies a calculation condition, which must be fulfilled for the measure
  /// to be calculated
  NxValueExpr qCalcCond;
}
