// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-11-15 11:30:01.492953

library sense_model.src.models.nx_donut;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxDonut {
  /// Set to present the pie chart as a donut.
  bool showAsDonut;
}
