// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.nx_field_attributes;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxFieldAttributes {
  /// Type of the field.Default is U
  String qType;

  /// Number of decimals. Default is 10
  int qnDec;

  /// Defines whether or not a thousands separator must be used
  int qUseThou;

  /// Defines the format pattern that applies to qText.Is used in connection to
  /// the type of the field
  String qFmt;

  /// Defines the decimal separator.
  String qDec;

  /// Defines the thousand separator (if any).Is used if qUseThou is set to 1.
  String qThou;
}
