// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.nx_generic_dimension_properties;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';
import 'nx_value_expr.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxGenericDimensionProperties {
  /// Array of field names.
  ///  When creating a grouped dimension, more than one field name is defined
  @Serialize.field('qInfo', optional: true)
  NxValueExpr qInfo;

  /// Array of field labels.
  @Serialize.field('qFieldLabels', optional: true)
  List<String> qFieldLabels;

  /// Used to define a cyclic group or drill-down group
  @Serialize.field('qGrouping', optional: true)
  String qGrouping;
}
