// Generated by Dogma Dart. DO NOT MODIFY!
// 2017-01-24 14:53:01.774400

library sense_model.src.models.nx_legend;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxLegend {
  /// Set to display the legend.
  @Serialize.field('show')
  bool show;

  /// Display the legend title
  @Serialize.field('showTitle', optional: true)
  bool showTitle;

  /// Sets the legend position
  @Serialize.field('dock', optional: true)
  String dock;
}
