// Generated by Dogma Dart. DO NOT MODIFY!
// 2017-01-17 11:59:03.825591

library sense_model.src.models.nx_library_measure_def;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxLibraryMeasureDef {
  /// Label of the measure.
  @Serialize.field('qLabel', optional: true)
  String qLabel;

  /// Definition of the measure.
  @Serialize.field('qDef')
  String qDef;

  /// Array of expressions.
  @Serialize.field('qExpressions', optional: true)
  List<String> qExpressions;

  /// Index to the active expression in a measure.
  @Serialize.field('qActiveExpression', optional: true)
  int qActiveExpression;

  /// Used to define a cyclic group or drill-down group
  @Serialize.field('qGrouping', optional: true)
  String qGrouping;
}
