// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-12-06 16:43:12.078728

library sense_model.src.models.nx_measure_series;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxMeasureSeries {
  /// Set how to visualize the series
  @Serialize.field('type')
  String type;
  @Serialize.field('axis', optional: true)
  int axis;
  @Serialize.field('marker', optional: true)
  String marker;
  @Serialize.field('markerFill', optional: true)
  bool markerFill;
}
