// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-11-11 17:56:46.338198

library sense_model.src.models.nx_ref_line_container;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'nx_ref_line.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxRefLineContainer {
  List<NxRefLine> refLines;
}
