// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-02 10:38:39.164902

library sense_model.src.models.nx_ref_line_container;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'nx_ref_line.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxRefLineContainer {
  List<NxRefLine> refLines;
}
