// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-08-19 12:36:50.431303

library sense_model.src.models.nx_ref_line_container;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'nx_ref_line.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxRefLineContainer {
  List<NxRefLine> refLines;
}
