// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-04 19:55:17.892601

library sense_model.src.models.nx_string_expr;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxStringExpr {
  /// Expression returning string value
  String qv;
}
