// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-11-15 11:30:01.492953

library sense_model.src.models.nx_string_expr;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxStringExpr {
  /// Expression returning string value
  String qv;
}
