// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.nx_sort_criteria;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'nx_value_expr.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxSortCriteria {
  /// Sort by expression
  int qSortByExpression;

  /// Sort by expression.
  NxValueExpr qExpression;

  /// Sorts the field values according to their logical state (selected,
  /// optional, alternative or excluded)
  int qSortByState;

  /// Sorts the field values by numeric value
  int qSortByFrequency;

  /// Sorts the field values according to their logical state (selected,
  /// optional, alternative or excluded)
  int qSortByNumeric;

  /// Sorts the field by alphabetical order
  int qSortByAscii;

  /// Sorts the field values by the initial load order
  int qSortByLoadOrder;
}
