// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.nx_sort_criteria;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxSortCriteria {
  /// Sorts the field values according to their logical state (selected,
  /// optional, alternative or excluded)
  int qSortByState;

  /// Sorts the field values by numeric value
  int qSortByFrequency;

  /// Sorts the field values according to their logical state (selected,
  /// optional, alternative or excluded)
  int qSortByNumeric;

  /// Sorts the field by alphabetical order
  int qSortByAscii;

  /// Sorts the field values by the initial load order
  int qSortByLoadOrder;

  /// Sort by expression
  int qSortByExpression;
}
