// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.nx_string_expr;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxStringExpr {
  /// Expression returning string value
  String qv;
}
