// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-04 19:55:17.892601

library sense_model.src.models.nx_value_expr;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxValueExpr {
  /// Expression returning number value
  String qv;
}
