// Generated by Dogma Dart. DO NOT MODIFY!
// 2017-01-24 14:53:01.774400

library sense_model.src.models.nx_value_expr;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxValueExpr {
  /// Expression returning number value
  String qv;
}
