// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-02 10:38:39.164902

library sense_model.src.models.nx_value_expr;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxValueExpr {
  /// Expression returning number value
  String qv;
}
