// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-02 10:38:39.164902

library sense_model.src.models.q_columns_container;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'nx_dimension.dart';
import 'nx_measure.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class QColumnsContainer {
  /// Dimensions
  List<NxDimension> qDimensions;

  /// Dimensions
  List<NxMeasure> qMeasures;
}
