// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-11-15 11:30:01.492953

library sense_model.src.models.q_columns_container;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'nx_dimension.dart';
import 'nx_measure.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class QColumnsContainer {
  /// Dimensions
  List<NxDimension> qDimensions;

  /// Dimensions
  List<NxMeasure> qMeasures;
}
