// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.q_hyper_cube_def;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';
import 'nx_dimension.dart';
import 'nx_measure.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class QHyperCubeDef {
  /// Dimensions
  @Serialize.field('qDimensions')
  List<NxDimension> qDimensions;

  /// Dimensions
  @Serialize.field('qMeasures')
  List<NxMeasure> qMeasures;

  /// Columns widths, -1 means autosize
  @Serialize.field('columnWidths', optional: true)
  List<int> columnWidths;

  /// Columns orders
  @Serialize.field('columnOrder', optional: true)
  List<int> columnOrder;
}
