// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.selection_table_data;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'selection_table_item.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class SelectionTableData {
  /// Код таблицы выбора
  String tableId;

  /// Тип выбираемого значения
  String tableType;
  List<SelectionTableItem> tableItems;
}
