// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.models.selection_table_item;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class SelectionTableItem {
  /// Код поля или выражения
  String value;

  /// Строка, которое будет отображаться в списке выбора
  String displayValue;
}
