// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_data_point_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxDataPoint].
class UnmodifiableNxDataPointView implements NxDataPoint {
  final NxDataPoint _model;

  UnmodifiableNxDataPointView(this._model);

  @override
  bool get show => _model.show;
  set show(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDataPoint');
  }
}
