// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_chart_definition_view;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:collection';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [ChartDefinition].
class UnmodifiableChartDefinitionView implements ChartDefinition {
  final ChartDefinition _model;
  final UnmodifiableListView<IvDimension> _dimensions;
  final UnmodifiableListView<IvMeasure> _measures;

  factory UnmodifiableChartDefinitionView(ChartDefinition model) {
    var dimensions = new UnmodifiableListView<IvDimension>(model.dimensions);
    var measures = new UnmodifiableListView<IvMeasure>(model.measures);
    return new UnmodifiableChartDefinitionView._internal(
        model, dimensions, measures);
  }

  UnmodifiableChartDefinitionView._internal(
      this._model, this._dimensions, this._measures);

  @override
  String get chartType => _model.chartType;
  set chartType(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable ChartDefinition');
  }

  @override
  String get chartId => _model.chartId;
  set chartId(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable ChartDefinition');
  }

  @override
  String get measuresSelector => _model.measuresSelector;
  set measuresSelector(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable ChartDefinition');
  }

  @override
  List<IvDimension> get dimensions => _dimensions;
  set dimensions(List<IvDimension> value) {
    throw new UnsupportedError('Cannot modify an unmodifiable ChartDefinition');
  }

  @override
  List<IvMeasure> get measures => _measures;
  set measures(List<IvMeasure> value) {
    throw new UnsupportedError('Cannot modify an unmodifiable ChartDefinition');
  }
}
