// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_legend_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxLegend].
class UnmodifiableNxLegendView implements NxLegend {
  final NxLegend _model;

  UnmodifiableNxLegendView(this._model);

  @override
  bool get show => _model.show;
  set show(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxLegend');
  }

  @override
  bool get showTitle => _model.showTitle;
  set showTitle(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxLegend');
  }

  @override
  String get dock => _model.dock;
  set dock(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxLegend');
  }
}
