// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_bar_grouping_view;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:collection';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxBarGrouping].
class UnmodifiableNxBarGroupingView implements NxBarGrouping {
  final NxBarGrouping _model;
  final UnmodifiableMapView _grouping;

  factory UnmodifiableNxBarGroupingView(NxBarGrouping model) {
    var grouping = new UnmodifiableMapView(model.grouping);
    return new UnmodifiableNxBarGroupingView._internal(model, grouping);
  }

  UnmodifiableNxBarGroupingView._internal(this._model, this._grouping);

  @override
  Map get grouping => _grouping;
  set grouping(Map value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxBarGrouping');
  }
}
