// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_value_expr_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxValueExpr].
class UnmodifiableNxValueExprView implements NxValueExpr {
  final NxValueExpr _model;

  UnmodifiableNxValueExprView(this._model);

  @override
  String get qv => _model.qv;
  set qv(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxValueExpr');
  }
}
