// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_grid_line_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxGridLine].
class UnmodifiableNxGridLineView implements NxGridLine {
  final NxGridLine _model;

  UnmodifiableNxGridLineView(this._model);

  @override
  bool get auto => _model.auto;
  set auto(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxGridLine');
  }

  @override
  int get spacing => _model.spacing;
  set spacing(int value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxGridLine');
  }
}
