// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_selection_table_item_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [SelectionTableItem].
class UnmodifiableSelectionTableItemView implements SelectionTableItem {
  final SelectionTableItem _model;

  UnmodifiableSelectionTableItemView(this._model);

  @override
  String get value => _model.value;
  set value(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable SelectionTableItem');
  }

  @override
  String get displayValue => _model.displayValue;
  set displayValue(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable SelectionTableItem');
  }
}
