// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_q_hyper_cube_def_view;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:collection';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [QHyperCubeDef].
class UnmodifiableQHyperCubeDefView implements QHyperCubeDef {
  final QHyperCubeDef _model;
  final UnmodifiableListView<NxDimension> _qDimensions;
  final UnmodifiableListView<int> _qInterColumnSortOrder;
  final UnmodifiableListView<NxMeasure> _qMeasures;
  final UnmodifiableListView<int> _columnWidths;
  final UnmodifiableListView<int> _columnOrder;

  factory UnmodifiableQHyperCubeDefView(QHyperCubeDef model) {
    var qDimensions = new UnmodifiableListView<NxDimension>(model.qDimensions);
    var qInterColumnSortOrder =
        new UnmodifiableListView<int>(model.qInterColumnSortOrder);
    var qMeasures = new UnmodifiableListView<NxMeasure>(model.qMeasures);
    var columnWidths = new UnmodifiableListView<int>(model.columnWidths);
    var columnOrder = new UnmodifiableListView<int>(model.columnOrder);
    return new UnmodifiableQHyperCubeDefView._internal(model, qDimensions,
        qInterColumnSortOrder, qMeasures, columnWidths, columnOrder);
  }

  UnmodifiableQHyperCubeDefView._internal(
      this._model,
      this._qDimensions,
      this._qInterColumnSortOrder,
      this._qMeasures,
      this._columnWidths,
      this._columnOrder);

  @override
  int get qSortbyYValue => _model.qSortbyYValue;
  set qSortbyYValue(int value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  int get qNoOfLeftDims => _model.qNoOfLeftDims;
  set qNoOfLeftDims(int value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  bool get qSuppressZero => _model.qSuppressZero;
  set qSuppressZero(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  bool get qSuppressMissing => _model.qSuppressMissing;
  set qSuppressMissing(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  bool get qAlwaysFullyExpanded => _model.qAlwaysFullyExpanded;
  set qAlwaysFullyExpanded(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  NxValueExpr get qCalcCond => _model.qCalcCond;
  set qCalcCond(NxValueExpr value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  bool get qShowTotalsAbove => _model.qShowTotalsAbove;
  set qShowTotalsAbove(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  bool get qIndentMode => _model.qIndentMode;
  set qIndentMode(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  List<NxDimension> get qDimensions => _qDimensions;
  set qDimensions(List<NxDimension> value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  List<int> get qInterColumnSortOrder => _qInterColumnSortOrder;
  set qInterColumnSortOrder(List<int> value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  List<NxMeasure> get qMeasures => _qMeasures;
  set qMeasures(List<NxMeasure> value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  List<int> get columnWidths => _columnWidths;
  set columnWidths(List<int> value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }

  @override
  List<int> get columnOrder => _columnOrder;
  set columnOrder(List<int> value) {
    throw new UnsupportedError('Cannot modify an unmodifiable QHyperCubeDef');
  }
}
