// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_library_dimension_def_view;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:collection';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxLibraryDimensionDef].
class UnmodifiableNxLibraryDimensionDefView implements NxLibraryDimensionDef {
  final NxLibraryDimensionDef _model;
  final UnmodifiableListView<String> _qFieldDefs;
  final UnmodifiableListView<String> _qFieldLabels;

  factory UnmodifiableNxLibraryDimensionDefView(NxLibraryDimensionDef model) {
    var qFieldDefs = new UnmodifiableListView<String>(model.qFieldDefs);
    var qFieldLabels = new UnmodifiableListView<String>(model.qFieldLabels);
    return new UnmodifiableNxLibraryDimensionDefView._internal(
        model, qFieldDefs, qFieldLabels);
  }

  UnmodifiableNxLibraryDimensionDefView._internal(
      this._model, this._qFieldDefs, this._qFieldLabels);

  @override
  String get qGrouping => _model.qGrouping;
  set qGrouping(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxLibraryDimensionDef');
  }

  @override
  List<String> get qFieldDefs => _qFieldDefs;
  set qFieldDefs(List<String> value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxLibraryDimensionDef');
  }

  @override
  List<String> get qFieldLabels => _qFieldLabels;
  set qFieldLabels(List<String> value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxLibraryDimensionDef');
  }
}
