// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_dimension_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxDimension].
class UnmodifiableNxDimensionView implements NxDimension {
  final NxDimension _model;

  UnmodifiableNxDimensionView(this._model);

  @override
  String get type => _model.type;
  set type(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDimension');
  }

  @override
  String get qLibraryId => _model.qLibraryId;
  set qLibraryId(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDimension');
  }

  @override
  NxInlineDimensionDef get qDef => _model.qDef;
  set qDef(NxInlineDimensionDef value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDimension');
  }

  @override
  bool get qNullSuppression => _model.qNullSuppression;
  set qNullSuppression(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDimension');
  }

  @override
  bool get qShowAll => _model.qShowAll;
  set qShowAll(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDimension');
  }

  @override
  String get qOtherLabel => _model.qOtherLabel;
  set qOtherLabel(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDimension');
  }

  @override
  String get qTotalLabel => _model.qTotalLabel;
  set qTotalLabel(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDimension');
  }

  @override
  String get qOtherTotalSpec => _model.qOtherTotalSpec;
  set qOtherTotalSpec(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDimension');
  }

  @override
  NxValueExpr get qCalcCond => _model.qCalcCond;
  set qCalcCond(NxValueExpr value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDimension');
  }
}
