// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_donut_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxDonut].
class UnmodifiableNxDonutView implements NxDonut {
  final NxDonut _model;

  UnmodifiableNxDonutView(this._model);

  @override
  bool get showAsDonut => _model.showAsDonut;
  set showAsDonut(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDonut');
  }
}
