// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_data_page_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxDataPage].
class UnmodifiableNxDataPageView implements NxDataPage {
  final NxDataPage _model;

  UnmodifiableNxDataPageView(this._model);

  @override
  String get qMatrix => _model.qMatrix;
  set qMatrix(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDataPage');
  }

  @override
  num get qNum => _model.qNum;
  set qNum(num value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDataPage');
  }

  @override
  int get qElemNumber => _model.qElemNumber;
  set qElemNumber(int value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDataPage');
  }

  @override
  String get qState => _model.qState;
  set qState(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDataPage');
  }

  @override
  bool get qIsEmpty => _model.qIsEmpty;
  set qIsEmpty(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDataPage');
  }

  @override
  bool get qIsTotalCell => _model.qIsTotalCell;
  set qIsTotalCell(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDataPage');
  }

  @override
  bool get qIsOtherCell => _model.qIsOtherCell;
  set qIsOtherCell(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDataPage');
  }

  @override
  String get qFrequency => _model.qFrequency;
  set qFrequency(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDataPage');
  }

  @override
  bool get qIsNull => _model.qIsNull;
  set qIsNull(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxDataPage');
  }
}
