// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_iv_dimension_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [IvDimension].
class UnmodifiableIvDimensionView implements IvDimension {
  final IvDimension _model;

  UnmodifiableIvDimensionView(this._model);

  @override
  bool get isStatic => _model.isStatic;
  set isStatic(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvDimension');
  }

  @override
  bool get dynamicHyerarchy => _model.dynamicHyerarchy;
  set dynamicHyerarchy(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvDimension');
  }

  @override
  String get contitional => _model.contitional;
  set contitional(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvDimension');
  }

  @override
  int get width => _model.width;
  set width(int value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvDimension');
  }

  @override
  IvMeasure get sortByExpression => _model.sortByExpression;
  set sortByExpression(IvMeasure value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvDimension');
  }

  @override
  bool get visible => _model.visible;
  set visible(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvDimension');
  }

  @override
  String get key => _model.key;
  set key(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvDimension');
  }
}
