// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_iv_measure_view;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:collection';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [IvMeasure].
class UnmodifiableIvMeasureView implements IvMeasure {
  final IvMeasure _model;
  final UnmodifiableListView<IvFilterParam> _filters;

  factory UnmodifiableIvMeasureView(IvMeasure model) {
    var filters = new UnmodifiableListView<IvFilterParam>(model.filters);
    return new UnmodifiableIvMeasureView._internal(model, filters);
  }

  UnmodifiableIvMeasureView._internal(this._model, this._filters);

  @override
  bool get isStatic => _model.isStatic;
  set isStatic(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvMeasure');
  }

  @override
  String get key => _model.key;
  set key(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvMeasure');
  }

  @override
  String get param => _model.param;
  set param(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvMeasure');
  }

  @override
  bool get conditional => _model.conditional;
  set conditional(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvMeasure');
  }

  @override
  bool get visible => _model.visible;
  set visible(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvMeasure');
  }

  @override
  List<IvFilterParam> get filters => _filters;
  set filters(List<IvFilterParam> value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvMeasure');
  }
}
