// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_field_attributes_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxFieldAttributes].
class UnmodifiableNxFieldAttributesView implements NxFieldAttributes {
  final NxFieldAttributes _model;

  UnmodifiableNxFieldAttributesView(this._model);

  @override
  String get qType => _model.qType;
  set qType(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxFieldAttributes');
  }

  @override
  int get qnDec => _model.qnDec;
  set qnDec(int value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxFieldAttributes');
  }

  @override
  int get qUseThou => _model.qUseThou;
  set qUseThou(int value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxFieldAttributes');
  }

  @override
  String get qFmt => _model.qFmt;
  set qFmt(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxFieldAttributes');
  }

  @override
  String get qDec => _model.qDec;
  set qDec(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxFieldAttributes');
  }

  @override
  String get qThou => _model.qThou;
  set qThou(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxFieldAttributes');
  }
}
