// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_iv_key_value_pair_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [IvKeyValuePair].
class UnmodifiableIvKeyValuePairView implements IvKeyValuePair {
  final IvKeyValuePair _model;

  UnmodifiableIvKeyValuePairView(this._model);

  @override
  String get key => _model.key;
  set key(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvKeyValuePair');
  }

  @override
  String get value => _model.value;
  set value(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvKeyValuePair');
  }
}
