// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_iv_filter_param_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [IvFilterParam].
class UnmodifiableIvFilterParamView implements IvFilterParam {
  final IvFilterParam _model;

  UnmodifiableIvFilterParamView(this._model);

  @override
  String get fieldName => _model.fieldName;
  set fieldName(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvFilterParam');
  }

  @override
  String get fieldValue => _model.fieldValue;
  set fieldValue(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable IvFilterParam');
  }
}
