// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_options_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxOptions].
class UnmodifiableNxOptionsView implements NxOptions {
  final NxOptions _model;

  UnmodifiableNxOptionsView(this._model);

  @override
  String get title => _model.title;
  set title(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxOptions');
  }

  @override
  bool get showTitles => _model.showTitles;
  set showTitles(bool value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxOptions');
  }

  @override
  String get subtitle => _model.subtitle;
  set subtitle(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxOptions');
  }

  @override
  String get footnote => _model.footnote;
  set footnote(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxOptions');
  }

  @override
  QHyperCubeDef get qHyperCubeDef => _model.qHyperCubeDef;
  set qHyperCubeDef(QHyperCubeDef value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxOptions');
  }
}
