// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_selection_table_data_view;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:collection';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [SelectionTableData].
class UnmodifiableSelectionTableDataView implements SelectionTableData {
  final SelectionTableData _model;
  final UnmodifiableListView<SelectionTableItem> _tableItems;

  factory UnmodifiableSelectionTableDataView(SelectionTableData model) {
    var tableItems =
        new UnmodifiableListView<SelectionTableItem>(model.tableItems);
    return new UnmodifiableSelectionTableDataView._internal(model, tableItems);
  }

  UnmodifiableSelectionTableDataView._internal(this._model, this._tableItems);

  @override
  String get tableId => _model.tableId;
  set tableId(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable SelectionTableData');
  }

  @override
  String get tableType => _model.tableType;
  set tableType(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable SelectionTableData');
  }

  @override
  bool get multiple => _model.multiple;
  set multiple(bool value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable SelectionTableData');
  }

  @override
  List<SelectionTableItem> get tableItems => _tableItems;
  set tableItems(List<SelectionTableItem> value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable SelectionTableData');
  }
}
