// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_inline_dimension_def_view;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:collection';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxInlineDimensionDef].
class UnmodifiableNxInlineDimensionDefView implements NxInlineDimensionDef {
  final NxInlineDimensionDef _model;
  final UnmodifiableListView<String> _qFieldDefs;
  final UnmodifiableListView<String> _qFieldLabels;
  final UnmodifiableListView<NxSortCriteria> _qSortCriterias;
  final UnmodifiableListView<NxFieldAttributes> _qNumberPresentations;

  factory UnmodifiableNxInlineDimensionDefView(NxInlineDimensionDef model) {
    var qFieldDefs = new UnmodifiableListView<String>(model.qFieldDefs);
    var qFieldLabels = new UnmodifiableListView<String>(model.qFieldLabels);
    var qSortCriterias =
        new UnmodifiableListView<NxSortCriteria>(model.qSortCriterias);
    var qNumberPresentations =
        new UnmodifiableListView<NxFieldAttributes>(model.qNumberPresentations);
    return new UnmodifiableNxInlineDimensionDefView._internal(
        model, qFieldDefs, qFieldLabels, qSortCriterias, qNumberPresentations);
  }

  UnmodifiableNxInlineDimensionDefView._internal(this._model, this._qFieldDefs,
      this._qFieldLabels, this._qSortCriterias, this._qNumberPresentations);

  @override
  String get qGrouping => _model.qGrouping;
  set qGrouping(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxInlineDimensionDef');
  }

  @override
  bool get qReverseSort => _model.qReverseSort;
  set qReverseSort(bool value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxInlineDimensionDef');
  }

  @override
  int get qActiveField => _model.qActiveField;
  set qActiveField(int value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxInlineDimensionDef');
  }

  @override
  List<String> get qFieldDefs => _qFieldDefs;
  set qFieldDefs(List<String> value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxInlineDimensionDef');
  }

  @override
  List<String> get qFieldLabels => _qFieldLabels;
  set qFieldLabels(List<String> value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxInlineDimensionDef');
  }

  @override
  List<NxSortCriteria> get qSortCriterias => _qSortCriterias;
  set qSortCriterias(List<NxSortCriteria> value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxInlineDimensionDef');
  }

  @override
  List<NxFieldAttributes> get qNumberPresentations => _qNumberPresentations;
  set qNumberPresentations(List<NxFieldAttributes> value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxInlineDimensionDef');
  }
}
