// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.unmodifiable_model_views.unmodifiable_nx_generic_dimension_properties_view;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:collection';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxGenericDimensionProperties].
class UnmodifiableNxGenericDimensionPropertiesView
    implements NxGenericDimensionProperties {
  final NxGenericDimensionProperties _model;
  final UnmodifiableListView<String> _qFieldLabels;

  factory UnmodifiableNxGenericDimensionPropertiesView(
      NxGenericDimensionProperties model) {
    var qFieldLabels = new UnmodifiableListView<String>(model.qFieldLabels);
    return new UnmodifiableNxGenericDimensionPropertiesView._internal(
        model, qFieldLabels);
  }

  UnmodifiableNxGenericDimensionPropertiesView._internal(
      this._model, this._qFieldLabels);

  @override
  NxValueExpr get qInfo => _model.qInfo;
  set qInfo(NxValueExpr value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxGenericDimensionProperties');
  }

  @override
  String get qGrouping => _model.qGrouping;
  set qGrouping(String value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxGenericDimensionProperties');
  }

  @override
  List<String> get qFieldLabels => _qFieldLabels;
  set qFieldLabels(List<String> value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable NxGenericDimensionProperties');
  }
}
