// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.convert.chart_definition_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';
import 'iv_dimension_convert.dart';
import 'iv_measure_convert.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [ChartDefinition].
class ChartDefinitionDecoder extends Converter<Map, ChartDefinition>
    implements ModelDecoder<ChartDefinition> {
  final Converter<Map, IvDimension> _ivDimensionDecoder;
  final Converter<Map, IvMeasure> _ivMeasureDecoder;
  ChartDefinitionDecoder()
      : _ivDimensionDecoder = new IvDimensionDecoder(),
        _ivMeasureDecoder = new IvMeasureDecoder();
  ChartDefinitionDecoder.using(
      this._ivDimensionDecoder, this._ivMeasureDecoder);
  @override
  ChartDefinition create() => new ChartDefinition();
  @override
  ChartDefinition convert(Map input, [ChartDefinition model]) {
    model ??= create();

    model.chartType = input['chartType'];
    model.chartId = input['chartId'];
    var dimensionsTemp0 = <IvDimension>[];
    for (var dimensionsValue0 in input['dimensions']) {
      dimensionsTemp0.add(_ivDimensionDecoder.convert(dimensionsValue0));
    }
    model.dimensions = dimensionsTemp0;
    model.measuresSelector = input['measuresSelector'];
    var measures = input['measures'];
    if (measures != null) {
      var measuresTemp0 = <IvMeasure>[];
      for (var measuresValue0 in measures) {
        measuresTemp0.add(_ivMeasureDecoder.convert(measuresValue0));
      }
      model.measures = measuresTemp0;
    }

    return model;
  }
}

/// A [ModelEncoder] for [ChartDefinition].
class ChartDefinitionEncoder extends Converter<ChartDefinition, Map>
    implements ModelEncoder<ChartDefinition> {
  final Converter<IvDimension, Map> _ivDimensionEncoder;
  final Converter<IvMeasure, Map> _ivMeasureEncoder;
  ChartDefinitionEncoder()
      : _ivDimensionEncoder = new IvDimensionEncoder(),
        _ivMeasureEncoder = new IvMeasureEncoder();
  ChartDefinitionEncoder.using(
      this._ivDimensionEncoder, this._ivMeasureEncoder);
  @override
  Map convert(ChartDefinition input) {
    var model = {};

    model['chartType'] = input.chartType;
    model['chartId'] = input.chartId;
    var dimensionsTemp0 = [];
    for (var dimensionsValue0 in input.dimensions) {
      dimensionsTemp0.add(_ivDimensionEncoder.convert(dimensionsValue0));
    }
    model['dimensions'] = dimensionsTemp0;
    var measuresSelector = input.measuresSelector;
    if (measuresSelector != null) {
      model['measuresSelector'] = measuresSelector;
    }
    var measures = input.measures;
    if (measures != null) {
      var measuresTemp0 = [];
      for (var measuresValue0 in measures) {
        measuresTemp0.add(_ivMeasureEncoder.convert(measuresValue0));
      }
      model['measures'] = measuresTemp0;
    }

    return model;
  }
}
