// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-11-15 11:30:01.492953

library sense_model.src.convert.iv_attr_expression_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';
import 'iv_expression_param_convert.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [IvAttrExpression].
class IvAttrExpressionDecoder extends Converter<Map, IvAttrExpression>
    implements ModelDecoder<IvAttrExpression> {
  final Converter<Map, IvExpressionParam> _ivExpressionParamDecoder;
  IvAttrExpressionDecoder()
      : _ivExpressionParamDecoder = new IvExpressionParamDecoder();
  IvAttrExpressionDecoder.using(this._ivExpressionParamDecoder);
  @override
  IvAttrExpression create() => new IvAttrExpression();
  @override
  IvAttrExpression convert(Map input, [IvAttrExpression model]) {
    model ??= create();

    model.expression = input['expression'];
    model.param1 = input['param1'];
    var params = input['params'];
    if (params != null) {
      var paramsTemp0 = <IvExpressionParam>[];
      for (var paramsValue0 in params) {
        paramsTemp0.add(_ivExpressionParamDecoder.convert(paramsValue0));
      }
      model.params = paramsTemp0;
    }
    model.inPlace = input['inPlace'];
    model.isStatic = input['isStatic'];
    return model;
  }
}

/// A [ModelEncoder] for [IvAttrExpression].
class IvAttrExpressionEncoder extends Converter<IvAttrExpression, Map>
    implements ModelEncoder<IvAttrExpression> {
  final Converter<IvExpressionParam, Map> _ivExpressionParamEncoder;
  IvAttrExpressionEncoder()
      : _ivExpressionParamEncoder = new IvExpressionParamEncoder();
  IvAttrExpressionEncoder.using(this._ivExpressionParamEncoder);
  @override
  Map convert(IvAttrExpression input) {
    var model = {};

    model['expression'] = input.expression;
    var param1 = input.param1;
    if (param1 != null) {
      model['param1'] = param1;
    }
    var params = input.params;
    if (params != null) {
      var paramsTemp0 = [];
      for (var paramsValue0 in params) {
        paramsTemp0.add(_ivExpressionParamEncoder.convert(paramsValue0));
      }
      model['params'] = paramsTemp0;
    }
    var inPlace = input.inPlace;
    if (inPlace != null) {
      model['inPlace'] = inPlace;
    }
    var isStatic = input.isStatic;
    if (isStatic != null) {
      model['isStatic'] = isStatic;
    }

    return model;
  }
}
