// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.convert.iv_dimension_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';
import 'iv_attr_expression_convert.dart';
import 'iv_measure_convert.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [IvDimension].
class IvDimensionDecoder extends Converter<Map, IvDimension>
    implements ModelDecoder<IvDimension> {
  final Converter<Map, IvMeasure> _ivMeasureDecoder;
  final Converter<Map, IvAttrExpression> _ivAttrExpressionDecoder;
  IvDimensionDecoder()
      : _ivMeasureDecoder = new IvMeasureDecoder(),
        _ivAttrExpressionDecoder = new IvAttrExpressionDecoder();
  IvDimensionDecoder.using(
      this._ivMeasureDecoder, this._ivAttrExpressionDecoder);
  @override
  IvDimension create() => new IvDimension();
  @override
  IvDimension convert(Map input, [IvDimension model]) {
    model ??= create();

    model.isStatic = input['isStatic'];
    model.dynamicHyerarchy = input['dynamicHyerarchy'];
    model.contitional = input['contitional'];
    model.width = input['width'];
    var sortByExpression = input['sortByExpression'];
    if (sortByExpression != null) {
      model.sortByExpression = _ivMeasureDecoder.convert(sortByExpression);
    }
    model.visible = input['visible'];
    var backgroundColor = input['backgroundColor'];
    if (backgroundColor != null) {
      model.backgroundColor = _ivAttrExpressionDecoder.convert(backgroundColor);
    }
    var fontColor = input['fontColor'];
    if (fontColor != null) {
      model.fontColor = _ivAttrExpressionDecoder.convert(fontColor);
    }
    model.key = input['key'];
    return model;
  }
}

/// A [ModelEncoder] for [IvDimension].
class IvDimensionEncoder extends Converter<IvDimension, Map>
    implements ModelEncoder<IvDimension> {
  final Converter<IvMeasure, Map> _ivMeasureEncoder;
  final Converter<IvAttrExpression, Map> _ivAttrExpressionEncoder;
  IvDimensionEncoder()
      : _ivMeasureEncoder = new IvMeasureEncoder(),
        _ivAttrExpressionEncoder = new IvAttrExpressionEncoder();
  IvDimensionEncoder.using(
      this._ivMeasureEncoder, this._ivAttrExpressionEncoder);
  @override
  Map convert(IvDimension input) {
    var model = {};

    var isStatic = input.isStatic;
    if (isStatic != null) {
      model['isStatic'] = isStatic;
    }
    var dynamicHyerarchy = input.dynamicHyerarchy;
    if (dynamicHyerarchy != null) {
      model['dynamicHyerarchy'] = dynamicHyerarchy;
    }
    var contitional = input.contitional;
    if (contitional != null) {
      model['contitional'] = contitional;
    }
    var width = input.width;
    if (width != null) {
      model['width'] = width;
    }
    var sortByExpression = input.sortByExpression;
    if (sortByExpression != null) {
      model['sortByExpression'] = _ivMeasureEncoder.convert(sortByExpression);
    }
    var visible = input.visible;
    if (visible != null) {
      model['visible'] = visible;
    }
    var backgroundColor = input.backgroundColor;
    if (backgroundColor != null) {
      model['backgroundColor'] =
          _ivAttrExpressionEncoder.convert(backgroundColor);
    }
    var fontColor = input.fontColor;
    if (fontColor != null) {
      model['fontColor'] = _ivAttrExpressionEncoder.convert(fontColor);
    }
    model['key'] = input.key;

    return model;
  }
}
