// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.convert.iv_filter_param_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [IvFilterParam].
class IvFilterParamDecoder extends Converter<Map, IvFilterParam>
    implements ModelDecoder<IvFilterParam> {
  @override
  IvFilterParam create() => new IvFilterParam();
  @override
  IvFilterParam convert(Map input, [IvFilterParam model]) {
    model ??= create();

    model.fieldName = input['fieldName'];
    model.fieldValue = input['fieldValue'];
    return model;
  }
}

/// A [ModelEncoder] for [IvFilterParam].
class IvFilterParamEncoder extends Converter<IvFilterParam, Map>
    implements ModelEncoder<IvFilterParam> {
  @override
  Map convert(IvFilterParam input) {
    var model = {};

    model['fieldName'] = input.fieldName;
    model['fieldValue'] = input.fieldValue;

    return model;
  }
}
