// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-04 19:55:17.892601

library sense_model.src.convert.iv_list_item_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [IvListItem].
class IvListItemDecoder extends Converter<Map, IvListItem>
    implements ModelDecoder<IvListItem> {
  @override
  IvListItem create() => new IvListItem();
  @override
  IvListItem convert(Map input, [IvListItem model]) {
    model ??= create();

    model.id = input['id'];
    model.title = input['title'];
    return model;
  }
}

/// A [ModelEncoder] for [IvListItem].
class IvListItemEncoder extends Converter<IvListItem, Map>
    implements ModelEncoder<IvListItem> {
  @override
  Map convert(IvListItem input) {
    var model = {};

    model['id'] = input.id;
    model['title'] = input.title;

    return model;
  }
}
