// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.convert.iv_measure_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';
import 'iv_filter_param_convert.dart';
import 'nx_measure_series_convert.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [IvMeasure].
class IvMeasureDecoder extends Converter<Map, IvMeasure>
    implements ModelDecoder<IvMeasure> {
  final Converter<Map, NxMeasureSeries> _nxMeasureSeriesDecoder;
  final Converter<Map, IvFilterParam> _ivFilterParamDecoder;
  IvMeasureDecoder()
      : _nxMeasureSeriesDecoder = new NxMeasureSeriesDecoder(),
        _ivFilterParamDecoder = new IvFilterParamDecoder();
  IvMeasureDecoder.using(
      this._nxMeasureSeriesDecoder, this._ivFilterParamDecoder);
  @override
  IvMeasure create() => new IvMeasure();
  @override
  IvMeasure convert(Map input, [IvMeasure model]) {
    model ??= create();

    model.isStatic = input['isStatic'];
    model.key = input['key'];
    model.param = input['param'];
    model.conditional = input['conditional'];
    model.width = input['width'];
    model.qRelative = input['qRelative'];
    model.qAccumulate = input['qAccumulate'];
    model.backgroundColor = input['backgroundColor'];
    model.fontColor = input['fontColor'];
    model.visible = input['visible'];
    var series = input['series'];
    if (series != null) {
      model.series = _nxMeasureSeriesDecoder.convert(series);
    }
    model.sortOrder = input['sortOrder'];
    var filters = input['filters'];
    if (filters != null) {
      var filtersTemp0 = <IvFilterParam>[];
      for (var filtersValue0 in filters) {
        filtersTemp0.add(_ivFilterParamDecoder.convert(filtersValue0));
      }
      model.filters = filtersTemp0;
    }

    return model;
  }
}

/// A [ModelEncoder] for [IvMeasure].
class IvMeasureEncoder extends Converter<IvMeasure, Map>
    implements ModelEncoder<IvMeasure> {
  final Converter<NxMeasureSeries, Map> _nxMeasureSeriesEncoder;
  final Converter<IvFilterParam, Map> _ivFilterParamEncoder;
  IvMeasureEncoder()
      : _nxMeasureSeriesEncoder = new NxMeasureSeriesEncoder(),
        _ivFilterParamEncoder = new IvFilterParamEncoder();
  IvMeasureEncoder.using(
      this._nxMeasureSeriesEncoder, this._ivFilterParamEncoder);
  @override
  Map convert(IvMeasure input) {
    var model = {};

    model['isStatic'] = input.isStatic;
    model['key'] = input.key;
    var param = input.param;
    if (param != null) {
      model['param'] = param;
    }
    var conditional = input.conditional;
    if (conditional != null) {
      model['conditional'] = conditional;
    }
    var width = input.width;
    if (width != null) {
      model['width'] = width;
    }
    var qRelative = input.qRelative;
    if (qRelative != null) {
      model['qRelative'] = qRelative;
    }
    var qAccumulate = input.qAccumulate;
    if (qAccumulate != null) {
      model['qAccumulate'] = qAccumulate;
    }
    var backgroundColor = input.backgroundColor;
    if (backgroundColor != null) {
      model['backgroundColor'] = backgroundColor;
    }
    var fontColor = input.fontColor;
    if (fontColor != null) {
      model['fontColor'] = fontColor;
    }
    var visible = input.visible;
    if (visible != null) {
      model['visible'] = visible;
    }
    var series = input.series;
    if (series != null) {
      model['series'] = _nxMeasureSeriesEncoder.convert(series);
    }
    var sortOrder = input.sortOrder;
    if (sortOrder != null) {
      model['sortOrder'] = sortOrder;
    }
    var filters = input.filters;
    if (filters != null) {
      var filtersTemp0 = [];
      for (var filtersValue0 in filters) {
        filtersTemp0.add(_ivFilterParamEncoder.convert(filtersValue0));
      }
      model['filters'] = filtersTemp0;
    }

    return model;
  }
}
