// Generated by Dogma Dart. DO NOT MODIFY!
// 2017-01-17 11:59:03.825591

library sense_model.src.convert.iv_master_dimension_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';
import 'locale_display_name_convert.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [IvMasterDimension].
class IvMasterDimensionDecoder extends Converter<Map, IvMasterDimension>
    implements ModelDecoder<IvMasterDimension> {
  final Converter<Map, LocaleDisplayName> _localeDisplayNameDecoder;
  IvMasterDimensionDecoder()
      : _localeDisplayNameDecoder = new LocaleDisplayNameDecoder();
  IvMasterDimensionDecoder.using(this._localeDisplayNameDecoder);
  @override
  IvMasterDimension create() => new IvMasterDimension();
  @override
  IvMasterDimension convert(Map input, [IvMasterDimension model]) {
    model ??= create();

    model.id = input['id'];
    model.title = input['title'];
    model.isCalculatedDimension = input['isCalculatedDimension'];
    var localeDisplayName = input['localeDisplayName'];
    if (localeDisplayName != null) {
      model.localeDisplayName =
          _localeDisplayNameDecoder.convert(localeDisplayName);
    }
    model.grouping = input['grouping'];
    model.width = input['width'];
    model.labels = input['labels'];
    model.fields = input['fields'];
    return model;
  }
}

/// A [ModelEncoder] for [IvMasterDimension].
class IvMasterDimensionEncoder extends Converter<IvMasterDimension, Map>
    implements ModelEncoder<IvMasterDimension> {
  final Converter<LocaleDisplayName, Map> _localeDisplayNameEncoder;
  IvMasterDimensionEncoder()
      : _localeDisplayNameEncoder = new LocaleDisplayNameEncoder();
  IvMasterDimensionEncoder.using(this._localeDisplayNameEncoder);
  @override
  Map convert(IvMasterDimension input) {
    var model = {};

    model['id'] = input.id;
    var title = input.title;
    if (title != null) {
      model['title'] = title;
    }
    var isCalculatedDimension = input.isCalculatedDimension;
    if (isCalculatedDimension != null) {
      model['isCalculatedDimension'] = isCalculatedDimension;
    }
    var localeDisplayName = input.localeDisplayName;
    if (localeDisplayName != null) {
      model['localeDisplayName'] =
          _localeDisplayNameEncoder.convert(localeDisplayName);
    }
    var grouping = input.grouping;
    if (grouping != null) {
      model['grouping'] = grouping;
    }
    var width = input.width;
    if (width != null) {
      model['width'] = width;
    }
    var labels = input.labels;
    if (labels != null) {
      model['labels'] = labels;
    }
    var fields = input.fields;
    if (fields != null) {
      model['fields'] = fields;
    }

    return model;
  }
}
