// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-04 19:55:17.892601

library sense_model.src.convert.iv_master_dimension_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [IvMasterDimension].
class IvMasterDimensionDecoder extends Converter<Map, IvMasterDimension>
    implements ModelDecoder<IvMasterDimension> {
  @override
  IvMasterDimension create() => new IvMasterDimension();
  @override
  IvMasterDimension convert(Map input, [IvMasterDimension model]) {
    model ??= create();

    model.id = input['id'];
    model.title = input['title'];
    model.grouping = input['grouping'];
    model.width = input['width'];
    model.labels = input['labels'];
    model.fields = input['fields'];
    return model;
  }
}

/// A [ModelEncoder] for [IvMasterDimension].
class IvMasterDimensionEncoder extends Converter<IvMasterDimension, Map>
    implements ModelEncoder<IvMasterDimension> {
  @override
  Map convert(IvMasterDimension input) {
    var model = {};

    model['id'] = input.id;
    var title = input.title;
    if (title != null) {
      model['title'] = title;
    }
    var grouping = input.grouping;
    if (grouping != null) {
      model['grouping'] = grouping;
    }
    var width = input.width;
    if (width != null) {
      model['width'] = width;
    }
    var labels = input.labels;
    if (labels != null) {
      model['labels'] = labels;
    }
    var fields = input.fields;
    if (fields != null) {
      model['fields'] = fields;
    }

    return model;
  }
}
