// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-04 19:55:17.892601

library sense_model.src.convert.iv_measure_type_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [IvMeasureType].
class IvMeasureTypeDecoder extends Converter<Map, IvMeasureType>
    implements ModelDecoder<IvMeasureType> {
  @override
  IvMeasureType create() => new IvMeasureType();
  @override
  IvMeasureType convert(Map input, [IvMeasureType model]) {
    model ??= create();

    model.key = input['key'];
    model.displayName = input['displayName'];
    model.isPlan = input['isPlan'];
    return model;
  }
}

/// A [ModelEncoder] for [IvMeasureType].
class IvMeasureTypeEncoder extends Converter<IvMeasureType, Map>
    implements ModelEncoder<IvMeasureType> {
  @override
  Map convert(IvMeasureType input) {
    var model = {};

    model['key'] = input.key;
    model['displayName'] = input.displayName;
    var isPlan = input.isPlan;
    if (isPlan != null) {
      model['isPlan'] = isPlan;
    }

    return model;
  }
}
