// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-04 19:55:17.892601

library sense_model.src.convert.iv_measure_family_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [IvMeasureFamily].
class IvMeasureFamilyDecoder extends Converter<Map, IvMeasureFamily>
    implements ModelDecoder<IvMeasureFamily> {
  @override
  IvMeasureFamily create() => new IvMeasureFamily();
  @override
  IvMeasureFamily convert(Map input, [IvMeasureFamily model]) {
    model ??= create();

    model.key = input['key'];
    model.displayName = input['displayName'];
    model.hasPlan = input['hasPlan'];
    model.monthly = input['monthly'];
    return model;
  }
}

/// A [ModelEncoder] for [IvMeasureFamily].
class IvMeasureFamilyEncoder extends Converter<IvMeasureFamily, Map>
    implements ModelEncoder<IvMeasureFamily> {
  @override
  Map convert(IvMeasureFamily input) {
    var model = {};

    model['key'] = input.key;
    model['displayName'] = input.displayName;
    var hasPlan = input.hasPlan;
    if (hasPlan != null) {
      model['hasPlan'] = hasPlan;
    }
    var monthly = input.monthly;
    if (monthly != null) {
      model['monthly'] = monthly;
    }

    return model;
  }
}
