// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-07 13:16:59.317938

library sense_model.src.convert.nx_dimension_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';
import 'nx_inline_dimension_def_convert.dart';
import 'nx_other_total_spec_prop_convert.dart';
import 'nx_value_expr_convert.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [NxDimension].
class NxDimensionDecoder extends Converter<Map, NxDimension>
    implements ModelDecoder<NxDimension> {
  final Converter<Map, NxInlineDimensionDef> _nxInlineDimensionDefDecoder;
  final Converter<Map, NxOtherTotalSpecProp> _nxOtherTotalSpecPropDecoder;
  final Converter<Map, NxValueExpr> _nxValueExprDecoder;
  NxDimensionDecoder()
      : _nxInlineDimensionDefDecoder = new NxInlineDimensionDefDecoder(),
        _nxOtherTotalSpecPropDecoder = new NxOtherTotalSpecPropDecoder(),
        _nxValueExprDecoder = new NxValueExprDecoder();
  NxDimensionDecoder.using(this._nxInlineDimensionDefDecoder,
      this._nxOtherTotalSpecPropDecoder, this._nxValueExprDecoder);
  @override
  NxDimension create() => new NxDimension();
  @override
  NxDimension convert(Map input, [NxDimension model]) {
    model ??= create();

    model.type = input['type'];
    model.qLibraryId = input['qLibraryId'];
    var qDef = input['qDef'];
    if (qDef != null) {
      model.qDef = _nxInlineDimensionDefDecoder.convert(qDef);
    }
    model.qNullSuppression = input['qNullSuppression'];
    model.autoSort = input['autoSort'];
    model.qShowAll = input['qShowAll'];
    model.qOtherLabel = input['qOtherLabel'];
    model.qTotalLabel = input['qTotalLabel'];
    var qOtherTotalSpec = input['qOtherTotalSpec'];
    if (qOtherTotalSpec != null) {
      model.qOtherTotalSpec =
          _nxOtherTotalSpecPropDecoder.convert(qOtherTotalSpec);
    }
    var qCalcCond = input['qCalcCond'];
    if (qCalcCond != null) {
      model.qCalcCond = _nxValueExprDecoder.convert(qCalcCond);
    }

    return model;
  }
}

/// A [ModelEncoder] for [NxDimension].
class NxDimensionEncoder extends Converter<NxDimension, Map>
    implements ModelEncoder<NxDimension> {
  final Converter<NxInlineDimensionDef, Map> _nxInlineDimensionDefEncoder;
  final Converter<NxOtherTotalSpecProp, Map> _nxOtherTotalSpecPropEncoder;
  final Converter<NxValueExpr, Map> _nxValueExprEncoder;
  NxDimensionEncoder()
      : _nxInlineDimensionDefEncoder = new NxInlineDimensionDefEncoder(),
        _nxOtherTotalSpecPropEncoder = new NxOtherTotalSpecPropEncoder(),
        _nxValueExprEncoder = new NxValueExprEncoder();
  NxDimensionEncoder.using(this._nxInlineDimensionDefEncoder,
      this._nxOtherTotalSpecPropEncoder, this._nxValueExprEncoder);
  @override
  Map convert(NxDimension input) {
    var model = {};

    var type = input.type;
    if (type != null) {
      model['type'] = type;
    }
    model['qLibraryId'] = input.qLibraryId;
    var qDef = input.qDef;
    if (qDef != null) {
      model['qDef'] = _nxInlineDimensionDefEncoder.convert(qDef);
    }
    var qNullSuppression = input.qNullSuppression;
    if (qNullSuppression != null) {
      model['qNullSuppression'] = qNullSuppression;
    }
    var autoSort = input.autoSort;
    if (autoSort != null) {
      model['autoSort'] = autoSort;
    }
    var qShowAll = input.qShowAll;
    if (qShowAll != null) {
      model['qShowAll'] = qShowAll;
    }
    var qOtherLabel = input.qOtherLabel;
    if (qOtherLabel != null) {
      model['qOtherLabel'] = qOtherLabel;
    }
    var qTotalLabel = input.qTotalLabel;
    if (qTotalLabel != null) {
      model['qTotalLabel'] = qTotalLabel;
    }
    var qOtherTotalSpec = input.qOtherTotalSpec;
    if (qOtherTotalSpec != null) {
      model['qOtherTotalSpec'] =
          _nxOtherTotalSpecPropEncoder.convert(qOtherTotalSpec);
    }
    var qCalcCond = input.qCalcCond;
    if (qCalcCond != null) {
      model['qCalcCond'] = _nxValueExprEncoder.convert(qCalcCond);
    }

    return model;
  }
}
