// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.convert.nx_dimension_1_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';
import 'nx_inline_dimension_def_convert.dart';
import 'nx_value_expr_convert.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [NxDimension1].
class NxDimension1Decoder extends Converter<Map, NxDimension1>
    implements ModelDecoder<NxDimension1> {
  final Converter<Map, NxInlineDimensionDef> _nxInlineDimensionDefDecoder;
  final Converter<Map, NxValueExpr> _nxValueExprDecoder;
  NxDimension1Decoder()
      : _nxInlineDimensionDefDecoder = new NxInlineDimensionDefDecoder(),
        _nxValueExprDecoder = new NxValueExprDecoder();
  NxDimension1Decoder.using(
      this._nxInlineDimensionDefDecoder, this._nxValueExprDecoder);
  @override
  NxDimension1 create() => new NxDimension1();
  @override
  NxDimension1 convert(Map input, [NxDimension1 model]) {
    model ??= create();

    model.type = input['type'];
    model.qLibraryId = input['qLibraryId'];
    model.qDef = _nxInlineDimensionDefDecoder.convert(input['qDef']);
    model.qNullSuppression = input['qNullSuppression'];
    model.qShowAll = input['qShowAll'];
    model.qOtherLabel = input['qOtherLabel'];
    model.qTotalLabel = input['qTotalLabel'];
    model.qOtherTotalSpec = input['qOtherTotalSpec'];
    model.qCalcCond = _nxValueExprDecoder.convert(input['qCalcCond']);

    return model;
  }
}

/// A [ModelEncoder] for [NxDimension1].
class NxDimension1Encoder extends Converter<NxDimension1, Map>
    implements ModelEncoder<NxDimension1> {
  final Converter<NxInlineDimensionDef, Map> _nxInlineDimensionDefEncoder;
  final Converter<NxValueExpr, Map> _nxValueExprEncoder;
  NxDimension1Encoder()
      : _nxInlineDimensionDefEncoder = new NxInlineDimensionDefEncoder(),
        _nxValueExprEncoder = new NxValueExprEncoder();
  NxDimension1Encoder.using(
      this._nxInlineDimensionDefEncoder, this._nxValueExprEncoder);
  @override
  Map convert(NxDimension1 input) {
    var model = {};

    model['type'] = input.type;
    model['qLibraryId'] = input.qLibraryId;
    model['qDef'] = _nxInlineDimensionDefEncoder.convert(input.qDef);
    model['qNullSuppression'] = input.qNullSuppression;
    model['qShowAll'] = input.qShowAll;
    model['qOtherLabel'] = input.qOtherLabel;
    model['qTotalLabel'] = input.qTotalLabel;
    model['qOtherTotalSpec'] = input.qOtherTotalSpec;
    model['qCalcCond'] = _nxValueExprEncoder.convert(input.qCalcCond);

    return model;
  }
}
