// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-11-15 11:30:01.492953

library sense_model.src.convert.nx_inline_measure_def_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';
import 'nx_field_attributes_convert.dart';
import 'nx_measure_series_convert.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [NxInlineMeasureDef].
class NxInlineMeasureDefDecoder extends Converter<Map, NxInlineMeasureDef>
    implements ModelDecoder<NxInlineMeasureDef> {
  final Converter<Map, NxFieldAttributes> _nxFieldAttributesDecoder;
  final Converter<Map, NxMeasureSeries> _nxMeasureSeriesDecoder;
  NxInlineMeasureDefDecoder()
      : _nxFieldAttributesDecoder = new NxFieldAttributesDecoder(),
        _nxMeasureSeriesDecoder = new NxMeasureSeriesDecoder();
  NxInlineMeasureDefDecoder.using(
      this._nxFieldAttributesDecoder, this._nxMeasureSeriesDecoder);
  @override
  NxInlineMeasureDef create() => new NxInlineMeasureDef();
  @override
  NxInlineMeasureDef convert(Map input, [NxInlineMeasureDef model]) {
    model ??= create();

    model.qLabel = input['qLabel'];
    model.qDescription = input['qDescription'];
    model.qDef = input['qDef'];
    model.qRelative = input['qRelative'];
    model.qBrutalSum = input['qBrutalSum'];
    model.qAggrFunc = input['qAggrFunc'];
    model.qAccumulate = input['qAccumulate'];
    model.qReverseSort = input['qReverseSort'];
    model.qActiveExpression = input['qActiveExpression'];
    model.qExpressions = input['qExpressions'];
    var qNumFormat = input['qNumFormat'];
    if (qNumFormat != null) {
      model.qNumFormat = _nxFieldAttributesDecoder.convert(qNumFormat);
    }
    var series = input['series'];
    if (series != null) {
      model.series = _nxMeasureSeriesDecoder.convert(series);
    }
    model.qTags = input['qTags'];
    return model;
  }
}

/// A [ModelEncoder] for [NxInlineMeasureDef].
class NxInlineMeasureDefEncoder extends Converter<NxInlineMeasureDef, Map>
    implements ModelEncoder<NxInlineMeasureDef> {
  final Converter<NxFieldAttributes, Map> _nxFieldAttributesEncoder;
  final Converter<NxMeasureSeries, Map> _nxMeasureSeriesEncoder;
  NxInlineMeasureDefEncoder()
      : _nxFieldAttributesEncoder = new NxFieldAttributesEncoder(),
        _nxMeasureSeriesEncoder = new NxMeasureSeriesEncoder();
  NxInlineMeasureDefEncoder.using(
      this._nxFieldAttributesEncoder, this._nxMeasureSeriesEncoder);
  @override
  Map convert(NxInlineMeasureDef input) {
    var model = {};

    var qLabel = input.qLabel;
    if (qLabel != null) {
      model['qLabel'] = qLabel;
    }
    var qDescription = input.qDescription;
    if (qDescription != null) {
      model['qDescription'] = qDescription;
    }
    model['qDef'] = input.qDef;
    var qRelative = input.qRelative;
    if (qRelative != null) {
      model['qRelative'] = qRelative;
    }
    var qBrutalSum = input.qBrutalSum;
    if (qBrutalSum != null) {
      model['qBrutalSum'] = qBrutalSum;
    }
    var qAggrFunc = input.qAggrFunc;
    if (qAggrFunc != null) {
      model['qAggrFunc'] = qAggrFunc;
    }
    var qAccumulate = input.qAccumulate;
    if (qAccumulate != null) {
      model['qAccumulate'] = qAccumulate;
    }
    var qReverseSort = input.qReverseSort;
    if (qReverseSort != null) {
      model['qReverseSort'] = qReverseSort;
    }
    var qActiveExpression = input.qActiveExpression;
    if (qActiveExpression != null) {
      model['qActiveExpression'] = qActiveExpression;
    }
    var qExpressions = input.qExpressions;
    if (qExpressions != null) {
      model['qExpressions'] = qExpressions;
    }
    var qNumFormat = input.qNumFormat;
    if (qNumFormat != null) {
      model['qNumFormat'] = _nxFieldAttributesEncoder.convert(qNumFormat);
    }
    var series = input.series;
    if (series != null) {
      model['series'] = _nxMeasureSeriesEncoder.convert(series);
    }
    var qTags = input.qTags;
    if (qTags != null) {
      model['qTags'] = qTags;
    }

    return model;
  }
}
