// Generated by Dogma Dart. DO NOT MODIFY!
// 2017-01-17 11:59:03.825591

library sense_model.src.convert.nx_info_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [NxInfo].
class NxInfoDecoder extends Converter<Map, NxInfo>
    implements ModelDecoder<NxInfo> {
  @override
  NxInfo create() => new NxInfo();
  @override
  NxInfo convert(Map input, [NxInfo model]) {
    model ??= create();

    model.qId = input['qId'];
    model.qType = input['qType'];
    return model;
  }
}

/// A [ModelEncoder] for [NxInfo].
class NxInfoEncoder extends Converter<NxInfo, Map>
    implements ModelEncoder<NxInfo> {
  @override
  Map convert(NxInfo input) {
    var model = {};

    model['qId'] = input.qId;
    var qType = input.qType;
    if (qType != null) {
      model['qType'] = qType;
    }

    return model;
  }
}
