// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-02 10:38:39.164902

library sense_model.src.convert.nx_legend_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [NxLegend].
class NxLegendDecoder extends Converter<Map, NxLegend>
    implements ModelDecoder<NxLegend> {
  @override
  NxLegend create() => new NxLegend();
  @override
  NxLegend convert(Map input, [NxLegend model]) {
    model ??= create();

    model.show = input['show'];
    model.showTitle = input['showTitle'];
    model.dock = input['dock'];
    return model;
  }
}

/// A [ModelEncoder] for [NxLegend].
class NxLegendEncoder extends Converter<NxLegend, Map>
    implements ModelEncoder<NxLegend> {
  @override
  Map convert(NxLegend input) {
    var model = {};

    model['show'] = input.show;
    var showTitle = input.showTitle;
    if (showTitle != null) {
      model['showTitle'] = showTitle;
    }
    var dock = input.dock;
    if (dock != null) {
      model['dock'] = dock;
    }

    return model;
  }
}
