// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.convert.nx_sort_criteria_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';
import 'nx_value_expr_convert.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [NxSortCriteria].
class NxSortCriteriaDecoder extends Converter<Map, NxSortCriteria>
    implements ModelDecoder<NxSortCriteria> {
  final Converter<Map, NxValueExpr> _nxValueExprDecoder;
  NxSortCriteriaDecoder() : _nxValueExprDecoder = new NxValueExprDecoder();
  NxSortCriteriaDecoder.using(this._nxValueExprDecoder);
  @override
  NxSortCriteria create() => new NxSortCriteria();
  @override
  NxSortCriteria convert(Map input, [NxSortCriteria model]) {
    model ??= create();

    model.qSortByExpression = input['qSortByExpression'];
    model.qExpression = _nxValueExprDecoder.convert(input['qExpression']);
    model.qSortByState = input['qSortByState'];
    model.qSortByFrequency = input['qSortByFrequency'];
    model.qSortByNumeric = input['qSortByNumeric'];
    model.qSortByAscii = input['qSortByAscii'];
    model.qSortByLoadOrder = input['qSortByLoadOrder'];
    return model;
  }
}

/// A [ModelEncoder] for [NxSortCriteria].
class NxSortCriteriaEncoder extends Converter<NxSortCriteria, Map>
    implements ModelEncoder<NxSortCriteria> {
  final Converter<NxValueExpr, Map> _nxValueExprEncoder;
  NxSortCriteriaEncoder() : _nxValueExprEncoder = new NxValueExprEncoder();
  NxSortCriteriaEncoder.using(this._nxValueExprEncoder);
  @override
  Map convert(NxSortCriteria input) {
    var model = {};

    model['qSortByExpression'] = input.qSortByExpression;
    model['qExpression'] = _nxValueExprEncoder.convert(input.qExpression);
    model['qSortByState'] = input.qSortByState;
    model['qSortByFrequency'] = input.qSortByFrequency;
    model['qSortByNumeric'] = input.qSortByNumeric;
    model['qSortByAscii'] = input.qSortByAscii;
    model['qSortByLoadOrder'] = input.qSortByLoadOrder;

    return model;
  }
}
