// Generated by Dogma Dart. DO NOT MODIFY!

library sense_model.src.convert.nx_sort_criteria_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [NxSortCriteria].
class NxSortCriteriaDecoder extends Converter<Map, NxSortCriteria>
    implements ModelDecoder<NxSortCriteria> {
  @override
  NxSortCriteria create() => new NxSortCriteria();
  @override
  NxSortCriteria convert(Map input, [NxSortCriteria model]) {
    model ??= create();

    model.qSortByState = input['qSortByState'];
    model.qSortByFrequency = input['qSortByFrequency'];
    model.qSortByNumeric = input['qSortByNumeric'];
    model.qSortByAscii = input['qSortByAscii'];
    model.qSortByLoadOrder = input['qSortByLoadOrder'];
    model.qSortByExpression = input['qSortByExpression'];
    return model;
  }
}

/// A [ModelEncoder] for [NxSortCriteria].
class NxSortCriteriaEncoder extends Converter<NxSortCriteria, Map>
    implements ModelEncoder<NxSortCriteria> {
  @override
  Map convert(NxSortCriteria input) {
    var model = {};

    model['qSortByState'] = input.qSortByState;
    model['qSortByFrequency'] = input.qSortByFrequency;
    model['qSortByNumeric'] = input.qSortByNumeric;
    model['qSortByAscii'] = input.qSortByAscii;
    model['qSortByLoadOrder'] = input.qSortByLoadOrder;
    model['qSortByExpression'] = input.qSortByExpression;

    return model;
  }
}
