// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-09-04 19:55:17.892601

library sense_model.src.convert.nx_string_expr_convert;

//---------------------------------------------------------------------
// Standard libraries
//---------------------------------------------------------------------

import 'dart:convert';

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/convert.dart';
import 'package:sense_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// A [ModelDecoder] for [NxStringExpr].
class NxStringExprDecoder extends Converter<Map, NxStringExpr>
    implements ModelDecoder<NxStringExpr> {
  @override
  NxStringExpr create() => new NxStringExpr();
  @override
  NxStringExpr convert(Map input, [NxStringExpr model]) {
    model ??= create();

    model.qv = input['qv'];
    return model;
  }
}

/// A [ModelEncoder] for [NxStringExpr].
class NxStringExprEncoder extends Converter<NxStringExpr, Map>
    implements ModelEncoder<NxStringExpr> {
  @override
  Map convert(NxStringExpr input) {
    var model = {};

    model['qv'] = input.qv;

    return model;
  }
}
